version: "3"

services:
    db:
        build: 
            context: .
            dockerfile: ./docker/db/Dockerfile
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            TZ: "Asia/Tokyo"
    wordpress:
        build:
            context: .
            dockerfile: ./docker/wp/Dockerfile
        depends_on:
            - db
        ports:
            - "8000:80"
        volumes:
        - "./www/html/:/var/www/html/"
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
    phpcs:
        build:
            context: .
            dockerfile: ./docker/phpcs/Dockerfile
        command: 
            - bash
        tty: true
        stdin_open: true
        volumes:
            - "./www/html/wp-content:/app"